### ISSUE TITLE
Create dashboard

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#75]
## User Story

**As a** user -  
**I want to** have a dashboard where I can see what's currently going on on the platform -  
**In order to** quickly engage in spontaneous communication.

## Conditions of satisfaction
- [x] The dashboard should contain placeholders for the following features:
  - [x] setting the own status (e.g. dropdown, top left) [#76]
  - [x] list of all users (not only contacts) filtered by status (left, 20% width) [#31]
  - [x] global chat, filtered by status (left-center, 40%) [#77]
  - [x] last activities  (center-right, 20%)
    - [x] creation (top) [#79]
    - [x] feed [#80]
  - [x] engagement proposals (right, 20%) / meeting invitations list [#37]
- [x] the dashboard should be displayed in a sensible manner on mobile screens
  - [x] a design for that is developed 
  - [x] the design is approved by PO
  - [x] the design is implemented

## Implementation Note

Filling the placeholders mentioned above ***is not*** part of this issue.

The design might look something like this (note that the content of this draft ***is not*** what is required to be implemented here. I rather put it for optical guidance).

![image](https://user-images.githubusercontent.com/47941549/101819147-207fb080-3b25-11eb-893c-1d84d537d3e9.png)

**Comment by mpass99** [comment]
![Bildschirmfoto von 2020-12-14 12-08-40](https://user-images.githubusercontent.com/22845248/102074499-33d09b80-3e05-11eb-9ed4-54ee35d67584.png)
Left: current state; Right: planning
